name: Ping Supabase

# Déclencheurs du workflow
on:
  schedule:
    - cron: '0 * * * *' # Exécute toutes les heures
  workflow_dispatch: # Permet l'exécution manuelle

jobs:
  ping-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Ou une autre version compatible avec votre code

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ping script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scripts/ping_supabase.py
